name: demo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # step 1: checkout the code from the github repository
      - name: checkout repository
        uses: actions/checkout@v2
 # step 2: Will verify docker access
      - name: verifying docker access
        run: docker --version
 # step 3: setting up docker buildx
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
 #step 4: building a docker image
      - name: build docker image
        run: |
          echo "bulding docker image"
          set -e #stop script first error
          docker build -t ehv-vault -f docker/Dockerfile .
        continue-on-error: false # Ensure the build errors stop the workflow
 #step 5: verify image
      - name: verify docker image
        run: docker images